# Generated by Django 4.2 on 2023-08-14 08:44

from django.db import migrations, models
import django.db.models.deletion
import shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(null=True, upload_to='order/receipts/'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shop_app.models.product_preview_directory_path),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop_app.models.product_images_directory_path)),
                ('discription_image', models.CharField(blank=True, max_length=150, verbose_name='Описание к картинке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_app.product')),
            ],
        ),
    ]
